[package]
name = "libp2p-relay-server"
version = "0.1.0"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.3"
futures = "0.3.1"
libp2p = { git = "https://github.com/mxinden/rust-libp2p", branch = "relay-v2" }
